sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t kennedy/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kennedy/docker-react npm run test -- --coverage --watchAll=false

deploy:
  skip_cleanup: true
  provider: script
  script: bash ./scripts/deploy.sh
  on:
    branch: