language: node_js
node_js:
  - "stable"
services:
  - docker

before_install:
  - docker build -t kennedy/docker-react -f Dockerfile.dev .

script:
  - docker run kennedy/docker-react npm run test -- --coverage

